FROM ruby:3.4.1-alpine3.21

WORKDIR /rails_textract

COPY Gemfile Gemfile.lock ./

RUN apk  --no-cache add linux-headers\
                        libxml2-dev\
                        make\
                        gcc\
                        libc-dev\
                        mysql-client \
                        mysql-dev \
                        nodejs\
                        tzdata\
                        sqlite\
                        git \
                        less \
                        curl \
                        coreutils \
                        gnupg \
                        imagemagick \
                        graphviz \
                        tmux \
                        go \
                        jemalloc \
                        yaml-dev \
                        openssl-dev \
                        yarn &&\
    apk add --virtual build-dependencies --no-cache build-base curl-dev &&\
    gem install bundler --no-document --version 2.6.2 && \
    bundle install -j4 &&\
    go install github.com/DarthSim/overmind/v2@latest &&\
    apk del build-dependencies

COPY . .

EXPOSE 3000
